scx:
  gateway:
    # 发送消息的超时时间(记录请求和响应日志时使用)
    send-timeout: 1000

#  配置中心的配置
spring:
  cloud:
    gateway:
      routes:
        - id: hlw                   # 路由 ID，唯一
          uri: lb://hlw-svr         # lb:// 根据服务名称从注册中心获取服务请求地址
          predicates:               # 断言（判断条件）
            - Path=/hlw/**          # 匹配对应 URL 的请求，将匹配到的请求追加在目标 URI 之后
        - id: rrl                   
          uri: lb://rrl-svr         
          predicates:               
            - Path=/rrl/**          
        - id: sgn                   
          uri: lb://sgn-svr         
          predicates:               
            - Path=/sgn/**          
        - id: rac                   
          uri: lb://rac-svr         
          predicates:               
            - Path=/rac/**          
          filters:
            - name: SignPre          # 签名前置过滤器
              args:
                ignore-urls:
                  - POST:/rac/sign-in/**