# 配置中心的配置
scx:
  gateway:
    # 发送消息的超时时间(发送添加请求和响应日志的消息时使用)
    send-timeout: 5000
    multipart:
      max-file-size:
        specifies:
          - url: "POST:/rac/account/upload-avatar"
            limit: 200KB

spring:
  cloud:
    gateway:
      discovery:
        locator:
          filters:
            - StripPrefix=1
            - name: SignPre
              args:
                filter-urls:
                  - "'/ctid/**'"
            - name: JwtPre
              args:
                filter-urls:
                  - "'/sgn/**'"
                  - "'/rac/**'"
                ignore-urls:
                  - "'POST:/rac/sign-in/**'"
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /