# 配置中心的配置
rrl:
  # 发送消息的超时时间(发送添加请求和响应日志的消息时使用)
  send-timeout: 1000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          filters:
            - StripPrefix=1
            - name: SignPre
              args:
                filter-urls:
                  - "'/ctid/**'"
            - name: JwtPre
              args:
                filter-urls:
                  - "'/rac/**'"
                ignore-urls:
                  - "'POST:/rac/sign-in/**'"
