# 配置中心的配置

scx:
  gateway:
    # 发送消息的超时时间(记录请求和响应日志时使用)
    send-timeout: 1000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          filters:
            - StripPrefix=1
            - name: SignPre
              args:
                filter-urls:
                  - "'/sgn/**'"
                ignore-urls:
                  - "'POST:/sgn/sign-in/**'"
