#  配置中心的配置
#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#      - id: hlw
#        uri: lb://hlw-svr
#        predicates:
#        - Path=/hlw-svr/**
#        filters:
#        - StripPrefix=1
