# 配置中心的配置

scx:
  gateway:
    # 发送消息的超时时间(记录请求和响应日志时使用)
    send-timeout: 1000

spring:
  cloud:
    gateway:
      routes:
        - id: rrl                   # 路由 ID，唯一                                  
          uri: lb://rrl-svr         # lb:// 根据服务名称从注册中心获取服务请求地址                 
          predicates:               # 断言（判断条件）                                  
            - Path=/rrl-svr/**      # 匹配对应 URL 的请求，将匹配到的请求追加在目标 URI 之后              
          filters:                  # 过滤器                                       
            - StripPrefix=1         # 路径去掉第一节来匹配微服务                             
        - id: sgn
          uri: lb://sgn-svr
          predicates:
            - Path=/sgn-svr/**
          filters:
            - StripPrefix=1
        - id: rac
          uri: lb://rac-svr
          predicates:
            - Path=/rac-svr/**
          filters:
            - StripPrefix=1
            - name: SignPre
              args:
                ignore-urls:
                  - POST:/rac/sign-in/**
