debug: true

server:
  port: 8761

logging:
  config: classpath:config/log4j2.xml
  level:
    root: info

eureka:
  client:
    # 下面两项实为关闭eureka客户端，表示是eureka的独立服务端
    register-with-eureka: false
    fetch-registry: false
  