## 此配置为集群版
server:
  port: 8761

logging:
  config: config/log4j2.xml
  level:
    root: info

eureka:
  instance:
    hostname: eureka-server-a
    # 客户端注册时使用IP而不是hostname(在客户端配置)
    prefer-ip-address: true
    # 将Instance ID设置成IP:端口的形式(在客户端配置)
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      # 这里填写其它节点的链接
      defaultZone: http://eureka-server-b:8762/eureka/,http://eureka-server-c:8763/eureka/  
  