# 配置中心中的配置
curator:
  connect-string: zookeeper_zoo1:2181,zookeeper_zoo2:2181,zookeeper_zoo3:2181

spring:
  datasource:
    url: jdbc:mysql://mysql_nginx:80/rac?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: rac
    password: ******
  rabbitmq:
    host: rabbitmq_rabbitmq
    port: 5672
    username: guest
    password: ******
    virtual-host: /
  redis:
    password: ******
    sentinel:
      # Redis服务器名称
      master: mymaster
      # 哨兵节点 
      nodes:
        - redis_sentinel1:6379
        - redis_sentinel2:6379
        - redis_sentinel3:6379
