# 配置中心中的配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sgn?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: sgn
    password: sgn
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  redis:
    host: 127.0.0.1
    port: 6379
    password: xxxxx