spring:
  profiles:
    active: dev

server:
  # config server启动的端口号
  port: 8888

#management:
#  context-path: /admin

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    statusPageUrlPath: /admin/info
#    healthCheckUrlPath: /admin/health