debug: true

logging:
  config: classpath:config/log4j2.xml
  level:
    root: info
    rebue: trace
    com.netflix.discovery: off

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          # git仓库地址
          uri: https://git.coding.net/rebue/config-center.git
          username: rebue@qq.com
          password: bbbc8760b9655f96b879c25209483233
