logging:
  config: config/log4j2.xml
  level:
    root: info
    rebue: trace
    org.apache.http: off
    com.netflix.discovery: off
    org.springframework.context.event.SimpleApplicationEventMulticaster: info
    org.springframework.dao: debug
    org.springframework.cloud: debug

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    
spring:
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest
  cloud:
    config:
      server:
        git:
          # git仓库地址
          uri: https://git.coding.net/cocmis/config-server.git
          username: cocmis
          password: CNBZT_cocmis.123#789
    bus:
      enabled: true
      trace:
        enabled: true # 开启消息跟踪
      refresh:
        enabled: true 
    
endpoints:
  bus-refresh:
    enabled: true
      